# Generated by Django 4.2.13 on 2024-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceriesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.DecimalField(blank=True, decimal_places=4, max_digits=14)),
                ('money_spent', models.DecimalField(decimal_places=4, max_digits=9)),
                ('purchase_date', models.DateField()),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('store_owner_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
