# Generated by Django 4.2.13 on 2024-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_data', '0003_groceriesinfo_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceriesinfo',
            name='product_name',
            field=models.CharField(help_text='Name of the Product/Produce/Goods', max_length=200),
        ),
    ]
