# Generated by Django 4.2.13 on 2024-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_data', '0005_alter_groceriesinfo_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceriesinfo',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
