# Generated by Django 4.2.13 on 2024-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_data', '0006_groceriesinfo_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceriesinfo',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
