# Generated by Django 4.2.13 on 2024-05-20 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groceries_data', '0010_groceriesinfo_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceriesinfo',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
