# Generated by Django 4.2.13 on 2024-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_data', '0012_alter_groceriesinfo_money_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceriesinfo',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='groceriesinfo',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
