# Generated by Django 4.2.13 on 2024-05-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_data', '0013_alter_groceriesinfo_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceriesinfo',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceriesinfo',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
